# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |d|
   d.has_ssh = true
   d.image = "bravit/mkn-os"
  end
  config.vm.synced_folder 'lab', '/home/vagrant/lab'
end
